config/routes.rb
Rails.application.routes.draw do
  resources :group_friends
  resources :groups
  resources :order_friends
  resources :orders
  resources :friendships
  post 'friendships/add_friend_by_name', to: 'friendships#add_friend_by_name'
  post 'order_friends/notifications_seen', to: 'order_friends#notifications_seen'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } 
  get 'welcome/index'
  root 'welcome#index'
end

app/models/group.rb
class Group < ApplicationRecord
    belongs_to :user
    has_many :group_friends
    has_many :users, through: :group_friends
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.where(user_id: current_user.id)
    @first_group = @groups.first()
    if @first_group
      @group_friends = GroupFriend.where(group_id: @first_group.id)
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group_friends = GroupFriend.where(group_id: @group.id)
    respond_to do |format|
      format.js {render layout: false}
    end
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = current_user.groups.build(name: params[:name], user_id: current_user.id)

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_url, notice: 'Group was successfully created.' }
        format.json { render :index, status: :created, location: @group }
      else
        format.html { redirect_to groups_url, notice: 'an Error Occured During add new Group' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:name)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/_listFriends.html.erb
<ul class="list-group">
    <% for friend in @group_friends %>
        <li class="list-group-item">
        <strong><%= friend.user.email%></strong>
        <%= link_to "Remove", group_friend_path(friend), :method => :delete,class: "btn btn-danger controllers" %>
        </li>
    <% end %>
</ul>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<html>
  <head>
    <%= stylesheet_link_tag "groups" %>
  </head>
  <div class="h1" style="background-color:lightskyblue;text-align:center;">
    <h1 style="color:white;">
      Groups Page
    </h1>
  </div>
  <body>
    <div id="bodycontainer">
      <div class="container">
        
        
        <%= form_tag(groups_path, method: "post",class: "form-inline") do %>
        <div class="col-auto my-4">
              <label style="color:white;font-size:25px;">
                Enter Your Group Name
              </label>
        </div>
          <%= text_field_tag(:name, "", class: "form-control col-5", placeholder: 'e.g OS Track')%>
          <div class="col-auto my-1">
            <%= submit_tag("Add Group",class: "btn btn-info") %>
          </div>
        <% end %>
        <% flash.each do |type, msg| %>
          <% if msg == "Group was successfully created." %>
            <div class="alert alert-success col-6">
              <%= msg %>
            </div>
          <% end %>
      <% end %>
        <div class="row">
          <div class="panel-body col-4">
            <h2 style="color:white;">Groups List</h2>
            <div>
              <ul class="list-group myBorder">
              <%if @groups.empty? %>
                <li class="list-group-item groups">
                <strong style="color:lightskyblue;"> There is no Groups Yet</strong>
                </li>

              <% else%>
                <% for group in @groups %>
                <li class="list-group-item groups">
                  <strong class="groupsName"><%= group.name %></strong>
                  <%= link_to 'X', group, method: :delete, data: { confirm: 'Are you Sure you want to Delete this Group?' },class: "btn btn-danger controllers" %>
                  <%= link_to 'Show', group_path(group), remote: true,class: "btn btn-info controllers" %>
                </li>
                <% end %>
            <%end%>
            </ul>
            </div>
          </div>
          <div class="panel-body col-8">
            <h2 style="color:white;">Friends List</h2>
            <div class="myBorder">
            
              <%= form_tag(group_friends_path, method: "post",class: "form-inline") do %>
            <div class="col-auto my-4">
                  <label style="color:white;">
                    Enter Your Friend Name
                  </label>
            </div>
              <%= text_field_tag(:user_email, "", class: "form-control col-5")%>
              <% if @groups[0]%>
                <%= hidden_field_tag(:group_id, @groups[0].id)%>  
              <% end %>
              <div class="col-auto my-1">
                <%= submit_tag("Add Friend",class: "btn btn-info") %>
              </div>
            <% end %>
              <div id="friendsList">
                  <ul class="list-group">
                  <% if @group_friends%>
                    <% for friend in @group_friends %>
                    <li class="list-group-item">
                      <strong><%= friend.user.email%></strong>
                      <%= link_to "Remove", group_friend_path(friend), :method => :delete,class: "btn btn-danger controllers" %>
                    </li>
                    <% end %>
                  <% else %>
                    <li class="list-group-item">
                      <strong style="color:lightskyblue;">Sorry There isn't Any Friend Yet</strong>
                    </li>
                  <% end %>
                    <% flash.each do |type, msg| %>
                      <% if msg == "Please Select Specified Group" %>
                        <div class="alert alert-danger col-6">
                          <%= msg %>
                        </div>
                      <% end %>
                      <% if msg == "Sorry this User Does Not Exist" %>
                        <div class="alert alert-success col-6">
                          <%= msg %>
                        </div>
                      <% end %>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </body>
</html>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @group.user_id %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app/views/groups/show.js.erb
$("#friendsList").empty();
$("#group_id").val("<%=@group.id%>");
$("#friendsList").html("<%= escape_javascript(render partial: 'groups/listFriends', locals: { group_friends: @group_friends } ) %>");