config/routes.rb
Rails.application.routes.draw do
  resources :group_friends
  resources :groups
  resources :order_friends
  resources :orders
  resources :friendships
  post 'friendships/add_friend_by_name', to: 'friendships#add_friend_by_name'
  post 'order_friends/notifications_seen', to: 'order_friends#notifications_seen'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } 
  get 'welcome/index'
  root 'welcome#index'
end

app/models/order_friend.rb
class OrderFriend < ApplicationRecord
    belongs_to :user
    belongs_to :order
end

app/controllers/order_friends_controller.rb
class OrderFriendsController < ApplicationController
  before_action :set_order_friend, only: [:show, :edit, :update, :destroy]

  # GET /order_friends
  # GET /order_friends.json
  def index
    @order_friends = OrderFriend.all
  end

  # GET /order_friends/1
  # GET /order_friends/1.json
  def show
  end

  # GET /order_friends/new
  def new
    @order_friend = OrderFriend.new
  end

  # GET /order_friends/1/edit
  def edit
  end

  # POST /order_friends
  # POST /order_friends.json
  def create
    @order_friend = OrderFriend.new(order_friend_params)

    respond_to do |format|
      if @order_friend.save
        format.html { redirect_to @order_friend, notice: 'Order friend was successfully created.' }
        format.json { render :show, status: :created, location: @order_friend }
      else
        format.html { render :new }
        format.json { render json: @order_friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_friends/1
  # PATCH/PUT /order_friends/1.json
  def update
    respond_to do |format|
      if @order_friend.update(order_friend_params)
        format.html { redirect_to @order_friend, notice: 'Order friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_friend }
      else
        format.html { render :edit }
        format.json { render json: @order_friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_friends/1
  # DELETE /order_friends/1.json
  def destroy
    @order_friend.destroy
    respond_to do |format|
      format.html { redirect_to order_friends_url, notice: 'Order friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def notifications_seen
    @my_notifications = OrderFriend.where(user_id: current_user.id).update_all(:seen => true)
    render json: {sayMyName: "Eslam"}
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_friend
      @order_friend = OrderFriend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_friend_params
      params.require(:order_friend).permit(:order_id, :user_id)
    end
end

app/helpers/order_friends_helper.rb
module OrderFriendsHelper
end

app/views/order_friends/_form.html.erb
<%= form_with(model: order_friend, local: true) do |form| %>
  <% if order_friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order_friend.errors.count, "error") %> prohibited this order_friend from being saved:</h2>

      <ul>
        <% order_friend.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :order_id %>
    <%= form.number_field :order_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/order_friends/edit.html.erb
<h1>Editing Order Friend</h1>

<%= render 'form', order_friend: @order_friend %>

<%= link_to 'Show', @order_friend %> |
<%= link_to 'Back', order_friends_path %>

app/views/order_friends/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Order Friends</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_friends.each do |order_friend| %>
      <tr>
        <td><%= order_friend.order_id %></td>
        <td><%= order_friend.user_id %></td>
        <td><%= link_to 'Show', order_friend %></td>
        <td><%= link_to 'Edit', edit_order_friend_path(order_friend) %></td>
        <td><%= link_to 'Destroy', order_friend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order Friend', new_order_friend_path %>

app/views/order_friends/new.html.erb
<h1>New Order Friend</h1>

<%= render 'form', order_friend: @order_friend %>

<%= link_to 'Back', order_friends_path %>

app/views/order_friends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @order_friend.order_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @order_friend.user_id %>
</p>

<%= link_to 'Edit', edit_order_friend_path(@order_friend) %> |
<%= link_to 'Back', order_friends_path %>