config/routes.rb
Rails.application.routes.draw do
  resources :group_friends
  resources :groups
  resources :order_friends
  resources :orders
  resources :friendships
  post 'friendships/add_friend_by_name', to: 'friendships#add_friend_by_name'
  post 'order_friends/notifications_seen', to: 'order_friends#notifications_seen'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } 
  get 'welcome/index'
  root 'welcome#index'
end

app/models/group_friend.rb
class GroupFriend < ApplicationRecord
    belongs_to :user
    belongs_to :group
end

app/controllers/group_friends_controller.rb
class GroupFriendsController < ApplicationController

  # GET /group_friends
  # GET /group_friends.json
  def index
    @group_friends = GroupFriend.all
  end

  # GET /group_friends/1
  # GET /group_friends/1.json
  def show
  end

  # GET /group_friends/new
  def new
    @group_friend = GroupFriend.new
  end

  # GET /group_friends/1/edit
  def edit
  end

  # POST /group_friends
  # POST /group_friends.json
  def create
    @added_user_to_group = User.find_by(email: params[:user_email])
    # @group = Group.find(params[:group_id])
    respond_to do |format|
      if params[:group_id].present?
        @group = Group.find(params[:group_id])
      else
        format.html { redirect_to groups_path, notice: 'Please Select Specified Group' }
      end
      if @added_user_to_group
        @add_new_user_to_group = GroupFriend.new(:group_id => @group.id, :user_id => @added_user_to_group.id)
        @add_new_user_to_group.save
        format.html { redirect_to groups_path, notice: 'User added Successfully' }
      else
        format.html { redirect_to groups_path, notice: 'Sorry this User Does Not Exist' }
      end
    end
  end

  # PATCH/PUT /group_friends/1
  # PATCH/PUT /group_friends/1.json
  def update
    respond_to do |format|
      if @group_friend.update(group_friend_params)
        format.html { redirect_to @group_friend, notice: 'Group friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @group_friend }
      else
        format.html { render :edit }
        format.json { render json: @group_friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /group_friends/1
  # DELETE /group_friends/1.json
  def destroy
    @group_friend = GroupFriend.find(params[:id])
    @group_friend.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group_friend
      @group_friend = GroupFriend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_friend_params
      params.require(:group_friend).permit(:group_id, :user_id)
    end
end

app/helpers/group_friends_helper.rb
module GroupFriendsHelper
end

app/views/group_friends/_form.html.erb
<%= form_with(model: group_friend, local: true) do |form| %>
  <% if group_friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group_friend.errors.count, "error") %> prohibited this group_friend from being saved:</h2>

      <ul>
        <% group_friend.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :group_id %>
    <%= form.number_field :group_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/group_friends/edit.html.erb
<h1>Editing Group Friend</h1>

<%= render 'form', group_friend: @group_friend %>

<%= link_to 'Show', @group_friend %> |
<%= link_to 'Back', group_friends_path %>

app/views/group_friends/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Group Friends</h1>

<table>
  <thead>
    <tr>
      <th>Group</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @group_friends.each do |group_friend| %>
      <tr>
        <td><%= group_friend.group_id %></td>
        <td><%= group_friend.user_id %></td>
        <td><%= link_to 'Show', group_friend %></td>
        <td><%= link_to 'Edit', edit_group_friend_path(group_friend) %></td>
        <td><%= link_to 'Destroy', group_friend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group Friend', new_group_friend_path %>

app/views/group_friends/new.html.erb
<h1>New Group Friend</h1>

<%= render 'form', group_friend: @group_friend %>

<%= link_to 'Back', group_friends_path %>

app/views/group_friends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Group:</strong>
  <%= @group_friend.group_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @group_friend.user_id %>
</p>

<%= link_to 'Edit', edit_group_friend_path(@group_friend) %> |
<%= link_to 'Back', group_friends_path %>